/**
 * Local-dev interview harness.
 *
 * Usage:
 *   bun apps/web/scripts/dev-interview-harness.ts
 *   bun apps/web/scripts/dev-interview-harness.ts --mode=audio
 *   bun apps/web/scripts/dev-interview-harness.ts --mode=video \
 *     --tavus-persona-id=p123 --tavus-replica-id=r456
 *   bun apps/web/scripts/dev-interview-harness.ts --scripted-timeline=comprehensive
 *
 * Flags:
 *   --mode=transcript|audio|video   (default: transcript)
 *       Sets the share-link `recordingConfig`. `audio` and `video` exercise
 *       the device-picker path; `video` additionally requires Tavus IDs.
 *   --tavus-persona-id=<id>         (only for --mode=video)
 *   --tavus-replica-id=<id>         (only for --mode=video)
 *   --scripted-timeline=basic|comprehensive   (default: basic)
 *       Which mock OpenAI Realtime timeline the harness should play
 *       during the consent → live → idle flow. `basic` is a fast smoke
 *       run (~30s, 4 tool calls); `comprehensive` exercises every tool
 *       category (~60s, 12 tool calls). Only used when LLM_PROVIDER=mock.
 *
 * Steps:
 *   1. Ensures `.env.local.dev-harness` exists with the env flags the
 *      seed-share-link endpoint and the magic-link capture path need.
 *   2. Boots `bun run dev` as a child process (port 3000) with that env
 *      merged on top of any existing `.env.local`.
 *   3. Polls `http://localhost:3000` until the dev server is ready.
 *   4. POSTs to `/api/v1/interviews/test-only/seed-share-link` to create
 *      a fresh share link bound to a test workspace, with the requested
 *      recordingConfig.
 *   5. Prints the consent URL so you can open it in a browser and walk
 *      the full guest flow without any auth.
 *   6. Stays running and forwards Ctrl-C to the dev server.
 *
 * Optional: set `LLM_PROVIDER=mock` in the harness env file (already on)
 * to route Anthropic / OpenAI calls to the in-process mock provider.
 */

import { spawn, type ChildProcess } from "node:child_process";
import { existsSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HARNESS_ENV_FILE = ".env.local.dev-harness";
const DEV_PORT = 3000;
const DEV_BASE_URL = `http://localhost:${DEV_PORT}`;
const SEED_ENDPOINT = "/api/v1/interviews/test-only/seed-share-link";

const HARNESS_ENV_DEFAULTS: Record<string, string> = {
  INTERVIEW_E2E_TEST_SEED: "true",
  INTERVIEW_MAGIC_LINK_TEST_CAPTURE: "true",
  LLM_PROVIDER: "mock",
  // Mock LLM keys — never used for real network calls when LLM_PROVIDER=mock,
  // but the @ai-sdk providers require *something* at construction time.
  ANTHROPIC_API_KEY: "mock-anthropic-key",
  OPENAI_API_KEY: "mock-openai-key",
  GOOGLE_GENERATIVE_AI_API_KEY: "mock-google-key",
};

function log(line: string): void {
  console.info(`[dev-interview-harness] ${line}`);
}

function err(line: string): void {
  console.error(`[dev-interview-harness] ${line}`);
}

/**
 * Locate the monorepo root by walking up from this script until we find
 * `apps/web`. We tolerate being invoked from any cwd.
 */
function findRepoRoot(): string {
  let dir = resolve(dirname(fileURLToPath(import.meta.url)));
  for (let i = 0; i < 6; i++) {
    if (existsSync(join(dir, "apps", "web", "package.json"))) {
      return dir;
    }
    dir = resolve(dir, "..");
  }
  throw new Error(
    "Could not locate monorepo root (looking for apps/web/package.json)",
  );
}

/**
 * Idempotently write `.env.local.dev-harness`. We never overwrite an
 * existing file — preserving any local edits the developer made.
 */
function ensureHarnessEnvFile(repoRoot: string): string {
  const filePath = join(repoRoot, HARNESS_ENV_FILE);
  if (existsSync(filePath)) {
    log(`Using existing harness env file: ${filePath}`);
    return filePath;
  }
  const body = Object.entries(HARNESS_ENV_DEFAULTS)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n");
  writeFileSync(
    filePath,
    `# Auto-generated by dev-interview-harness.ts\n# Edit freely — the harness only creates this if it does not exist.\n${body}\n`,
  );
  log(`Created harness env file: ${filePath}`);
  return filePath;
}

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf-8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) out[key] = value;
  }
  return out;
}

async function waitForServer(baseUrl: string, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(baseUrl, {
        method: "GET",
        signal: AbortSignal.timeout(2000),
      });
      // Any HTTP response means the server is up (even 404 / 500).
      if (res.status > 0) return;
    } catch {
      // Connection refused — server not ready yet.
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(
    `Dev server did not respond on ${baseUrl} within ${timeoutMs}ms`,
  );
}

interface SeedResponse {
  token: string;
  shareLinkId: string;
}

type RecordingMode = "transcript" | "audio" | "video";
type ScriptedTimelineMode = "basic" | "comprehensive";

interface CliOptions {
  mode: RecordingMode;
  tavusPersonaId?: string;
  tavusReplicaId?: string;
  scriptedTimeline: ScriptedTimelineMode;
}

export function parseCliArgs(argv: string[]): CliOptions {
  let mode: RecordingMode = "transcript";
  let tavusPersonaId: string | undefined;
  let tavusReplicaId: string | undefined;
  let scriptedTimeline: ScriptedTimelineMode = "basic";

  for (const arg of argv) {
    const eq = arg.indexOf("=");
    if (eq === -1) continue;
    const key = arg.slice(0, eq);
    const value = arg.slice(eq + 1);
    switch (key) {
      case "--mode": {
        if (value !== "transcript" && value !== "audio" && value !== "video") {
          throw new Error(
            `Invalid --mode value "${value}". Use transcript|audio|video.`,
          );
        }
        mode = value;
        break;
      }
      case "--tavus-persona-id":
        tavusPersonaId = value;
        break;
      case "--tavus-replica-id":
        tavusReplicaId = value;
        break;
      case "--scripted-timeline": {
        if (value !== "basic" && value !== "comprehensive") {
          throw new Error(
            `Invalid --scripted-timeline value "${value}". Use basic|comprehensive.`,
          );
        }
        scriptedTimeline = value;
        break;
      }
      default:
        // Unknown flag — ignore so future flags don't break older callers.
        break;
    }
  }

  if (mode === "video" && (!tavusPersonaId || !tavusReplicaId)) {
    throw new Error(
      "--mode=video requires both --tavus-persona-id=<id> and --tavus-replica-id=<id>.",
    );
  }

  return { mode, tavusPersonaId, tavusReplicaId, scriptedTimeline };
}

export async function seedShareLink(
  baseUrl: string,
  options: CliOptions,
): Promise<SeedResponse> {
  const res = await fetch(`${baseUrl}${SEED_ENDPOINT}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      visibility: "link",
      authMode: "anonymous",
      recordingConfig: options.mode,
      topic: "dev-harness test workspace",
      workspaceId: "dev-harness",
      ...(options.tavusPersonaId
        ? { tavusPersonaId: options.tavusPersonaId }
        : {}),
      ...(options.tavusReplicaId
        ? { tavusReplicaId: options.tavusReplicaId }
        : {}),
    }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(
      `seed-share-link failed (${res.status}): ${text.slice(0, 200)}`,
    );
  }
  return (await res.json()) as SeedResponse;
}

async function main(): Promise<void> {
  let cliOptions: CliOptions;
  try {
    cliOptions = parseCliArgs(process.argv.slice(2));
  } catch (error) {
    err((error as Error).message);
    process.exit(2);
  }

  const repoRoot = findRepoRoot();
  const harnessEnvPath = ensureHarnessEnvFile(repoRoot);

  const harnessEnv = parseEnvFile(harnessEnvPath);
  const childEnv: NodeJS.ProcessEnv = {
    ...process.env,
    ...harnessEnv,
    PORT: String(DEV_PORT),
    // Forward the chosen mock timeline shape into the dev server's env so
    // the consent route mints a `mock-<id>:<mode>` ephemeral token that
    // matches the harness selection.
    INTERVIEW_MOCK_TIMELINE: cliOptions.scriptedTimeline,
  };

  log("Starting dev server (`bun run dev`) — this may take ~10s…");

  const dev: ChildProcess = spawn("bun", ["run", "dev"], {
    cwd: join(repoRoot, "apps", "web"),
    env: childEnv,
    stdio: ["ignore", "inherit", "inherit"],
  });

  const cleanup = (code = 0): void => {
    if (!dev.killed) {
      log("Stopping dev server…");
      dev.kill("SIGTERM");
    }
    process.exit(code);
  };

  process.on("SIGINT", () => cleanup(0));
  process.on("SIGTERM", () => cleanup(0));
  dev.on("exit", (code) => {
    err(`dev server exited unexpectedly with code ${code ?? "null"}`);
    process.exit(code ?? 1);
  });

  try {
    await waitForServer(DEV_BASE_URL, 60_000);
    log(`Dev server up at ${DEV_BASE_URL}`);

    if (childEnv.LLM_PROVIDER === "mock") {
      log(
        `Mock mode active — no real LLM spend (LLM_PROVIDER=mock, scripted-timeline=${cliOptions.scriptedTimeline})`,
      );
    }

    const seed = await seedShareLink(DEV_BASE_URL, cliOptions);
    const consentUrl = `${DEV_BASE_URL}/i/${seed.token}/consent`;

    log(`Seeded interview with recordingConfig=${cliOptions.mode}`);
    log("");
    log("====================================================");
    log("Share link ready. Open this URL in a browser:");
    log("");
    log(`  ${consentUrl}`);
    log("");
    log(`  shareLinkId:       ${seed.shareLinkId}`);
    log(`  token:             ${seed.token}`);
    log(`  recordingConfig:   ${cliOptions.mode}`);
    log(`  scriptedTimeline:  ${cliOptions.scriptedTimeline}`);
    log("====================================================");
    log("");
    log("Press Ctrl-C to stop the dev server.");
  } catch (error) {
    err(`Setup failed: ${(error as Error).message}`);
    cleanup(1);
  }
}

// Only auto-run when invoked as the entry point (i.e. `bun apps/web/scripts/dev-interview-harness.ts`).
// Importing this file from a test must NOT spawn a dev server.
const isDirectInvocation =
  typeof process !== "undefined" &&
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (isDirectInvocation) {
  void main();
}
