import "server-only";
import type Anthropic from "@anthropic-ai/sdk";

/**
 * Minimal in-process Anthropic mock for the local dev-interview harness.
 *
 * Activated when `LLM_PROVIDER=mock` and `NODE_ENV !== "production"`.
 * The shape mirrors the surface the writer-worker, follow-up-suggester,
 * and async-stitcher actually exercise: `client.messages.create(...)`
 * returning an object whose `content[]` is `[{type: "text", text: ... }]`.
 *
 * The text payload is deterministic and depends on the system + user
 * messages passed in, so the writer pipeline produces *something*
 * realistic-looking (a JSON `WriterDiff[]` array, a JSON suggestion
 * array, or a JSON CanvasState) without burning real Anthropic spend.
 */

type AnthropicMessagesParam = Parameters<Anthropic["messages"]["create"]>[0];
type AnthropicMessageResponse = Awaited<
  ReturnType<Anthropic["messages"]["create"]>
>;

/**
 * Best-effort heuristic that classifies the call site from the messages
 * payload so the mock can return a JSON shape the caller can parse.
 *
 * - `writer-worker` system prompt contains "WriterDiff" — return `[]`.
 * - `follow-up-suggester` system prompt asks for `text`/`rationale` —
 *   return a one-item suggestion array.
 * - `async-stitcher` system prompt asks for `CanvasState` JSON — return
 *   a minimal stitched CanvasState.
 * - Otherwise: a generic non-empty text block so callers that just want
 *   any successful response keep working.
 */
function classifyCall(params: AnthropicMessagesParam): "writer" | "follow-ups" | "stitcher" | "generic" {
  const system = params.system;
  let systemText = "";
  if (typeof system === "string") {
    systemText = system;
  } else if (Array.isArray(system)) {
    systemText = system
      .map((block) => (block.type === "text" ? block.text : ""))
      .join("\n");
  }
  if (systemText.includes("WriterDiff")) return "writer";
  if (systemText.includes("follow-up") || systemText.includes("rationale")) {
    return "follow-ups";
  }
  if (systemText.includes("CanvasState") || systemText.includes("CanvasSection")) {
    return "stitcher";
  }
  return "generic";
}

function buildMockText(params: AnthropicMessagesParam): string {
  switch (classifyCall(params)) {
    case "writer":
      // Empty diff array — the writer's parseDiffs accepts this shape
      // and treats it as "no changes warranted", which is the safest
      // outcome for a no-op mock that still exercises the parse path.
      return "[]";
    case "follow-ups":
      return JSON.stringify([
        {
          text: "(mock) Tell me more about that.",
          rationale:
            "Deterministic mock follow-up from LLM_PROVIDER=mock — no real Claude call.",
        },
      ]);
    case "stitcher":
      return JSON.stringify({
        title: "(mock) Async interview stitched by LLM_PROVIDER=mock",
        sections: [
          {
            id: "section-1",
            heading: "Mock section",
            bullets: [],
            paragraphs: [
              "This article body comes from the in-process Anthropic mock, not a real Claude call.",
            ],
            quotes: [],
            finalized: true,
          },
        ],
        meta: {
          description: "Generated by the dev-interview-harness mock provider.",
          tags: ["mock"],
          suggestedCategory: null,
        },
      });
    case "generic":
    default:
      return "(mock) deterministic response from LLM_PROVIDER=mock";
  }
}

/**
 * Construct the mock client. The return type is widened to the real
 * Anthropic class via a cast at the call site — we only implement the
 * `messages.create` slice the codebase uses, and TypeScript's structural
 * compatibility would fail against the full SDK surface.
 */
export function createMockAnthropic(): Pick<Anthropic, "messages"> {
  return {
    messages: {
      create: (async (params: AnthropicMessagesParam) => {
        const text = buildMockText(params);
        const response = {
          id: `msg_mock_${Date.now()}`,
          type: "message",
          role: "assistant",
          model: params.model,
          content: [{ type: "text", text }],
          stop_reason: "end_turn",
          stop_sequence: null,
          usage: { input_tokens: 0, output_tokens: 0 },
        };
        return response as unknown as AnthropicMessageResponse;
      }) as Anthropic["messages"]["create"],
    } as Anthropic["messages"],
  };
}
