import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { PATCH } from "./route";

const mockGetArticleBySlug = vi.hoisted(() => vi.fn());
const mockUpdateArticleBySlug = vi.hoisted(() => vi.fn());

vi.mock("@/lib/articles/repository", () => ({
  getArticleBySlug: mockGetArticleBySlug,
  updateArticleBySlug: mockUpdateArticleBySlug,
  deleteArticleBySlug: vi.fn(),
}));

// Mock createApiHandler to pass blogId and expose session
vi.mock("@/lib/create-api-handler", () => {
  return {
    createApiHandler: ({ handler }: { handler: (args: { request: NextRequest; body: unknown; params: Record<string, string>; session: { uid: string; role: string }; blogId: string; role: string | null }) => Promise<Response> }) => {
      return async (req: NextRequest, ctx: { params: Promise<Record<string, string>> }) => {
        const mockSession = { uid: "user-123", role: "user" };
        const params = await ctx.params;
        let body = undefined;
        try {
          body = await req.json();
        } catch (_e) {
          // ignore
        }
        return handler({ request: req, body, params, session: mockSession, blogId: "default", role: "user" });
      };
    },
  };
});

const mockGetBlogConfig = vi.hoisted(() => vi.fn());
vi.mock("@/lib/blog-config", () => ({
  getBlogConfig: mockGetBlogConfig,
}));

const mockPreparePublishedArticleUpdate = vi.hoisted(() => vi.fn());
vi.mock("@/lib/article-publish", () => ({
  preparePublishedArticleUpdate: mockPreparePublishedArticleUpdate,
}));

const mockSendGuestPublishedEmail = vi.hoisted(() => vi.fn());
vi.mock("@/lib/interviews/send-guest-published-email", () => ({
  sendGuestPublishedEmail: mockSendGuestPublishedEmail,
}));

describe("PATCH /api/v1/articles/[slug]", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    delete process.env.NEXT_PUBLIC_BASE_URL;

    mockGetBlogConfig.mockResolvedValue({
      domain: "blogbat.com",
    });

    mockPreparePublishedArticleUpdate.mockResolvedValue({
      body: "<p>Published body</p>",
      wordCount: 150,
      readingTime: 1,
      submissionStatus: {
        indexNow: {
          status: "pending",
          lastSubmittedAt: null,
          lastUrl: null,
          lastError: null,
        },
      },
    });

    // Mock updateArticleBySlug to return the updated article
    mockUpdateArticleBySlug.mockResolvedValue({
      id: "article-123",
      status: "published",
      slug: "my-article",
    });
  });

  it("should send guest article published email when interview article is published with guest email", async () => {
    mockGetArticleBySlug.mockResolvedValue({
      id: "article-123",
      slug: "my-article",
      title: "My Article Title",
      generatedBy: "interview",
      guestAttribution: {
        name: "Jane Doe",
        email: "jane@example.com",
      },
      status: "draft",
      body: "",
      draftBody: "",
      category: "",
      versions: [],
    });

    const req = new NextRequest("http://localhost/api/v1/articles/my-article", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "publish" }),
    });

    const res = await PATCH(req, { params: Promise.resolve({ slug: "my-article" }) });
    expect(res.status).toBe(200);

    // Verify it called sendGuestPublishedEmail
    expect(mockSendGuestPublishedEmail).toHaveBeenCalledTimes(1);
    expect(mockSendGuestPublishedEmail).toHaveBeenCalledWith({
      to: "jane@example.com",
      guestName: "Jane Doe",
      articleTitle: "My Article Title",
      articleUrl: "https://blogbat.com/my-article",
    });
  });

  it("should handle guestName being missing or null gracefully", async () => {
    mockGetArticleBySlug.mockResolvedValue({
      id: "article-123",
      slug: "my-article",
      title: "My Article Title",
      generatedBy: "interview",
      guestAttribution: {
        email: "jane@example.com",
      },
      status: "draft",
      body: "",
      draftBody: "",
      category: "",
      versions: [],
    });

    const req = new NextRequest("http://localhost/api/v1/articles/my-article", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "publish" }),
    });

    const res = await PATCH(req, { params: Promise.resolve({ slug: "my-article" }) });
    expect(res.status).toBe(200);

    expect(mockSendGuestPublishedEmail).toHaveBeenCalledTimes(1);
    expect(mockSendGuestPublishedEmail).toHaveBeenCalledWith({
      to: "jane@example.com",
      guestName: null,
      articleTitle: "My Article Title",
      articleUrl: "https://blogbat.com/my-article",
    });
  });

  it("should NOT send email if article was NOT generated by interview", async () => {
    mockGetArticleBySlug.mockResolvedValue({
      id: "article-123",
      slug: "my-article",
      title: "My Article Title",
      generatedBy: "manual",
      guestAttribution: {
        name: "Jane Doe",
        email: "jane@example.com",
      },
      status: "draft",
      body: "",
      draftBody: "",
      category: "",
      versions: [],
    });

    const req = new NextRequest("http://localhost/api/v1/articles/my-article", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "publish" }),
    });

    const res = await PATCH(req, { params: Promise.resolve({ slug: "my-article" }) });
    expect(res.status).toBe(200);

    // Verify it did NOT call sendGuestPublishedEmail
    expect(mockSendGuestPublishedEmail).not.toHaveBeenCalled();
  });

  it("should NOT send email if interview article is missing guestAttribution email", async () => {
    mockGetArticleBySlug.mockResolvedValue({
      id: "article-123",
      slug: "my-article",
      title: "My Article Title",
      generatedBy: "interview",
      status: "draft",
      body: "",
      draftBody: "",
      category: "",
      versions: [],
    });

    const req = new NextRequest("http://localhost/api/v1/articles/my-article", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "publish" }),
    });

    const res = await PATCH(req, { params: Promise.resolve({ slug: "my-article" }) });
    expect(res.status).toBe(200);

    expect(mockSendGuestPublishedEmail).not.toHaveBeenCalled();
  });

  it("should not fail publishing if email sending throws an error", async () => {
    mockGetArticleBySlug.mockResolvedValue({
      id: "article-123",
      slug: "my-article",
      title: "My Article Title",
      generatedBy: "interview",
      guestAttribution: {
        name: "Jane Doe",
        email: "jane@example.com",
      },
      status: "draft",
      body: "",
      draftBody: "",
      category: "",
      versions: [],
    });

    mockSendGuestPublishedEmail.mockRejectedValue(new Error("Email system offline"));

    const req = new NextRequest("http://localhost/api/v1/articles/my-article", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "publish" }),
    });

    const res = await PATCH(req, { params: Promise.resolve({ slug: "my-article" }) });
    expect(res.status).toBe(200); // Publish succeeds despite email error

    expect(mockSendGuestPublishedEmail).toHaveBeenCalledTimes(1);
  });
});
